[package]
name = "pglite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
fallible-iterator = "0.2"
postgres-protocol = "0.6"
wasmer = "3.1.1"
wasmer-emscripten = "3.1.1"
wasmer-wasi = "3.1.1"

[dev-dependencies]
wasmparser = "0.216"
