[package]
name = "pglite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
fallible-iterator = "0.2"
postgres-protocol = "0.6"
wasmer = "5.0.0-rc.1"
wasmer-emscripten = "5.0.0-rc.1"
regex = "1"

[dev-dependencies]
wasmparser = "0.216"
