[package]
name = "dbschema"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hcl = { package = "hcl-rs", version = "0.16" }
regex = "1"
toml = "0.8"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
sha2 = "0.10"
base64 = "0.22"
md5 = "0.7"
walkdir = "2"
path-absolutize = "3"
postgres = "0.19"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 3
