name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install just
      run: sudo apt-get update && sudo apt-get install -y just

    - name: Run tests
      run: cargo test

    - name: Run example tests
      run: just examples-test
